### ISSUE TITLE
请问登录一直认证失败是因为什么啊

### ISSUE THREAD

**Issue by Emporio-a** [zhjcreator/fetch_lecture#5]

**Comment by zhjcreator** [comment]
东大更新了登录方式，导致原有的登录方式失效了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月5日(周日) 中午1:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhjcreator/fetch_lecture] 请问登录一直认证失败是因为什么啊 (Issue #5)
