### ISSUE TITLE
进行post之后获得的内容转为json出问题

### ISSUE THREAD

**Issue by William-island** [zhjcreator/fetch_lecture#8]
sesson进行post之后获得的内容转为json出问题是什么原因啊大佬，因为这个没抢到
![image](https://github.com/zhjcreator/fetch_lecture/assets/56476937/c1c555e7-8f74-43a1-b0fa-37766b33b868)

**Comment by DgntYang** [comment]
目前上次更新版本手动改下cookie也还能用，包括抢和捡漏，放在压缩包里了。最新版本提交UID和验证码表单那块好像有点问题，等大佬解决。
[fetch_lecture.zip](https://github.com/zhjcreator/fetch_lecture/files/13308560/fetch_lecture.zip)

**Comment by Golevka2001** [comment]
目前无法测试，等下轮预约开始时再修，试试 @DgntYang 提供的的上个版本的代码？我这边测出来没有发现缺少 cookies 的问题

**Comment by Golevka2001** [comment]
已修复，可在 [Pull requests #10](https://github.com/zhjcreator/fetch_lecture/pull/10) 查看变动内容：更新请求头中 `Content-Type` 为 `application/x-www-form-urlencoded`。

本地测试通过，如问题仍存在欢迎继续反馈。
